# Generated by Django 5.2.1 on 2026-03-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
